import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full">
        {children}
        <Toaster
          position="top-center"
          swipeDirections={["right", "left", "top"]}
          toastOptions={{
            style: {
              background: "#1a1a1a",
              border: "1px solid #2a2a2a",
              color: "#a3a3a3",
              fontFamily: "monospace",
              fontSize: "13px",
            },
          }}
        />
      </body>
    </html>
  );
}
